# Generated by Django 3.2.3 on 2021-09-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausername', models.CharField(max_length=30)),
                ('apassword', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
